

import React from "react";
import Contactform from "./contactform";

export const metadata = {
  title: "Contact Us",
  description: "Generated by kirat IT",
};

export default function ContactUs() {
  return (
    <div>
      <div className="bg-secondary-lightGray bg-[url('/bg1.png')]">
        <div className="container mx-auto 2xl:px-32 px-8">
          <div className="flex flex-col md:flex-row">
            <div className="md:w-1/2 md:mb-0 mb-8">
              <h2 className="block text-primary-midnightBlue font-bold md:text-4xl text-2xl uppercase md:mt-20 mt-12">
                Contact{" "}
                <span className="text-primary-orange font-bold md:text-4xl text-2xl uppercase">
                  Us
                </span>
              </h2>
            </div>
            <Contactform />
          </div>
        </div>
      </div>
      <div className="container mx-auto 2xl:px-32 px-8 xl:py-28 py-8">
        <div className="flex justify-between flex-col md:flex-row mb-16 px-28 md:text-left text-center">
          <div className="md:w-1/3 mb-8 xl:mr-16 mr-0">
            <img className="mb-4 inline" src="/icon1.png" alt="no img" />
            <h3 className="font-extrabold text-xl mb-2">PHONE NO.</h3>
            <p>
              <a href="tel:+918500007126" className=" text-sm block">
              +918500007126
              </a>
            </p>
          </div>
          <div className="md:w-1/3 mb-8 xl:mr-16 mr-0">
            <img className="mb-4 inline " src="/icon2.png" alt="no img" />
            <h3 className="font-extrabold text-xl mb-2">EMAIL </h3>
            <p className="text-sm ">
              <a href="mailto:hr@kiratitsolutions.com">hello@kiratlearning.com</a>
            </p>
          </div>

          <div className="md:w-1/3 mb-8 xl:mr-16 mr-0 ">
            <img className="mb-4 inline" src="/icon3.png" alt="no img" />
            <h3 className="font-extrabold text-xl mb-2">ADDRESS</h3>
            <div className="flex flex-col gap-2">
              <p className="text-sm">
                Kirat Information Technology LLC, PO BOX - 111409, Dubai, United
                Arab Emirates,
                <br /> Phone- +918500007126
              </p>
              <p className="text-sm">
                Kirat IT, UK - 127 Fencepiece Road, Ilford, England, IG6 2LD
              </p>
              
            </div>
          </div>
        </div>
        
      </div>
    </div>
  );
}
